import type { Metadata } from "next";
import { Analytics } from '@vercel/analytics/next';
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Home • Schumacher Design",
  description: "Generated by create next app",
  keywords: ['Next.js', 'React', 'JavaScript'],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Analytics />         
        <Footer />
      </body>
    </html>
  );
}
